### PR TITLE
fix: remove dependency on tweetnacl

### LINKED ISSUE #30: Suggestion: Change verifyKey function to be pure JS friendly
Hello, 
The current implementation of verify key function has Buffer as typeof accepted input which are NodeJS specific and require heavy polyfills for pure JS (serverless/service-workers) 

We can instead use 
```typescript
import * as ed from "@noble/ed25519"

const verifyKey = async (
  signature: string,
  timestamp: string,
  body: string,
  clientPublicKey: string
) => {
  const message = new TextEncoder().encode(timestamp + body)
  const isVerified = await ed.verify(signature, message, clientPublicKey)
  return isVerified
}

export default verifyKey
```
Cons:
 - change the argument types 
 - dependent library 

Pros:
 - now can be used in service-workers or pure JS environment

### LINKED ISSUE #54: Replace `tweetnacl` with `discord-verify`
The tweetnacl library has a massive impact on bot performance due to its usage of non-native code. [`discord-verify`](https://www.npmjs.com/package/discord-verify) uses new native methods for verification that results in a dramatic performance increase.

This was the real world performance benefits the Truth or Dare bot saw when they swapped off of `discord-interactions` and deployed `discord-verify`:

image

The library also protects against additional security concerns such as replay attacks.

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This change drops the dependency on tweetnacl for key verification, instead relying on the node.js built-in Ed25519 implementation.  This seems to work locally with node 18+, but needs to be tested in other environments.  

I'm not sure this is a good idea.  The ed225519 support in node **22** is still experimental, and this will drop a console warning on startup:
https://nodejs.org/api/webcrypto.html#ed25519ed448x25519x448-key-pairs

- [x] Set a correct minimum version of node.js in engines
- [x] Verify it works as expected with Cloudflare workers
- [x] Ship a preview version of the package before 4.x to let people try it out first
- [ ] Make sure to update the changelog to call out the breaking change for making `verifyKey` async

Fixes #30 and generally resolves #54

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
alpha is now available at https://www.npmjs.com/package/discord-interactions/v/4.0.0-alpha.0

File: src/__tests__/verifyKey.ts [hunk 1]
```diff
@@ -1,170 +1,167 @@
...
-				'example invalid body',
-				signedRequest.signature,
-				String(Math.round(new Date().getTime() / 1000) - 10000),
-				validKeyPair.publicKey,
-			),
-		).toBe(false);
+			validKeyPair.privateKey,
+		);
+		const isValid = await verifyKey(
+			'example invalid body',
```
Comment (smol-skyz) [inline src/__tests__/verifyKey.ts:129]: I somehow managed to mess up this unit test back in January of 2021 and it has gone unnoticed until now. This should be `signedRequest.body` instead of the invalid body, since we should only be supplying an invalid timestamp for this one.

Comment (JustinBeckwith) [reply src/__tests__/verifyKey.ts]: hey, thanks!

**Review by goatslacker — APPROVED** [review]

File: src/util.ts [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+ * @param format - Format of value. Valid options: 'hex'. Defaults to utf-8.
+ * @returns Value in Uint8Array form.
+ */
+export function valueToUint8Array(
+	value: Uint8Array | ArrayBuffer | Buffer | string,
+	format?: string,
+): Uint8Array {
+	if (value == null) {
+		return new Uint8Array();
+	}
```
Comment (appellation) [inline src/util.ts:41]: This is illegal in the types; are we doing this to protect against JS users?

File: src/util.ts [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+	if (typeof globalThis !== 'undefined' && globalThis.crypto) {
+		return globalThis.crypto.subtle;
+	}
+	if (typeof crypto !== 'undefined') {
+		return crypto.subtle;
+	}
+	if (typeof require === 'function') {
+		// Cloudflare workers are doing what appears to be a regex check to look and
+		// warn for this pattern. We should never get her in a cloudflare worker, so
```
[the remark this answers is not in the document]
Comment (JustinBeckwith) [reply src/util.ts:17]: 🤦‍♂️

File: src/util.ts [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+	if (value == null) {
+		return new Uint8Array();
+	}
+	if (typeof value === 'string') {
+		if (format === 'hex') {
+			const matches = value.match(/.{1,2}/g);
+			if (matches == null) {
+				throw new Error('Value is not a valid hex string');
+			}
+			const hexVal = matches.map((byte: string) => Number.parseInt(byte, 16));
```
Comment (appellation) [inline src/util.ts:48]: This is kind of insane. Is this really the best approach 😆

File: src/util.ts [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+		}
+
+		return new TextEncoder().encode(value);
+	}
+	try {
+		if (Buffer.isBuffer(value)) {
+			return new Uint8Array(value);
+		}
+	} catch (ex) {
+		// Runtime doesn't have Buffer
```
Comment (appellation) [inline src/util.ts:59]: Should we do a `typeof Buffer !== 'undefined'` check here in case we're swallowing exceptions?

**Review by appellation — APPROVED** [review]

File: src/util.ts (hunk 2 above)
Comment (JustinBeckwith) [reply src/util.ts:41]: I would assume as such, yes.  This function was copypasta'd from `index.ts`, in it's exact same form.  I didn't change of it.

File: src/util.ts (hunk 4 above)
Comment (JustinBeckwith) [reply src/util.ts:48]: dude ... if you can find a better approach that works I'm all ears.  This is a copy/paste from the original code, just shifted over.  I tried doing some other clever things with `btoa` and `TextEncoder`, but the whole "hex string" thing threw me for a loop.

File: src/util.ts (hunk 5 above)
Comment (JustinBeckwith) [reply src/util.ts:59]: I can't imagine what other kind of exception could happen in this very narrow use case
